import { useEffect, useState } from "react";

export default function KRV6Addons(){
  const [tab,setTab]=useState("health"),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
  const [health,setHealth]=useState(null),[score,setScore]=useState(null),[report,setReport]=useState(null),[analytics,setAnalytics]=useState(null),[updates,setUpdates]=useState(null),[memories,setMemories]=useState([]),[shots,setShots]=useState([]);
  useEffect(()=>{runHealth()},[]);
  async function j(url,opt){const r=await fetch(url,opt);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||d.reply||"Request failed");return d}
  async function runHealth(){setBusy(true);setMsg("");try{setHealth(await j("/api/health-monitor"));setTab("health")}catch(e){setMsg(e.message)}setBusy(false)}
  async function loadScore(){setBusy(true);setMsg("");try{setScore(await j("/api/trading-scorecard"));setTab("scorecard")}catch(e){setMsg(e.message)}setBusy(false)}
  async function coinReport(){const coin=prompt("Coin/project to research?");if(!coin)return;setBusy(true);setMsg("");try{setReport(await j("/api/coin-report",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({coin})}));setTab("coin")}catch(e){setMsg(e.message)}setBusy(false)}
  async function loadAnalytics(){setBusy(true);setMsg("");try{setAnalytics(await j("/api/command-analytics"));setTab("analytics")}catch(e){setMsg(e.message)}setBusy(false)}
  async function selfUpdate(){const goal=prompt("What should K-R improve/add?");if(!goal)return;setBusy(true);setMsg("");try{setUpdates(await j("/api/self-update-suggest",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal})}));setTab("updates")}catch(e){setMsg(e.message)}setBusy(false)}
  async function loadMemory(){setBusy(true);setMsg("");try{const d=await j("/api/memory-rank");setMemories(d.memories||[]);setTab("memory")}catch(e){setMsg(e.message)}setBusy(false)}
  async function saveMemory(){const content=prompt("What should K-R remember?");if(!content)return;const importance=prompt("Importance? low / medium / high / critical","high")||"high";setBusy(true);try{await j("/api/memory-rank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,tag:"voice_note",importance})});await loadMemory()}catch(e){setMsg(e.message)}setBusy(false)}
  async function loadShots(){setBusy(true);setMsg("");try{const d=await j("/api/screenshot-history");setShots(d.items||[]);setTab("shots")}catch(e){setMsg(e.message)}setBusy(false)}
  return <div className="v6"><style>{css}</style><div className="v6top"><div><h2>K‑R v6 Smart Upgrades</h2><p>Add-only layer: health, scorecards, ranked memory, coin reports, analytics, self-update assistant.</p></div><button onClick={runHealth}>Refresh</button></div>
  <div className="v6actions"><button onClick={runHealth}>Health</button><button onClick={loadScore}>Scorecard</button><button onClick={coinReport}>Coin Report</button><button onClick={loadAnalytics}>Analytics</button><button onClick={selfUpdate}>Self-Update</button><button onClick={loadMemory}>Memory Rank</button><button onClick={saveMemory}>Add Memory</button><button onClick={loadShots}>Screenshots</button></div>
  <div className="v6tabs">{["health","scorecard","coin","analytics","updates","memory","shots"].map(x=><button key={x} className={tab===x?"a":""} onClick={()=>setTab(x)}>{x}</button>)}</div>{busy&&<div className="v6note">K‑R working...</div>}{msg&&<div className="v6note">{msg}</div>}
  {tab==="health"&&<Card title="Website / System Health"><pre>{JSON.stringify(health||{},null,2)}</pre></Card>}
  {tab==="scorecard"&&<Card title="Trading Scorecard">{score?<><div className="v6grid mini"><div>Trades<br/><b>{score.totalTrades}</b></div><div>Win Rate<br/><b>{score.winRate}%</b></div><div>Best Pair<br/><b>{score.bestPair||"n/a"}</b></div><div>Worst Pair<br/><b>{score.worstPair||"n/a"}</b></div></div><pre>{JSON.stringify(score.insights||[],null,2)}</pre></>:<p>Click Scorecard.</p>}</Card>}
  {tab==="coin"&&<Card title="Coin Research Report">{report?<><p><b>{report.coin}</b></p><div className="v6summary">{report.report}</div></>:<p>Click Coin Report.</p>}</Card>}
  {tab==="analytics"&&<Card title="K-R Command Analytics"><pre>{JSON.stringify(analytics||{},null,2)}</pre></Card>}
  {tab==="updates"&&<Card title="Self-Update Assistant"><div className="v6summary">{updates?.plan||"Click Self-Update."}</div></Card>}
  {tab==="memory"&&<Card title="Memory Importance Ranking">{memories.length?memories.map(m=><div className="v6row" key={m.id}><b>{m.importance||"medium"}</b> · {m.content}<br/><small>{m.tag}</small></div>):<p>No ranked memory yet.</p>}</Card>}
  {tab==="shots"&&<Card title="Screenshot History">{shots.length?shots.map(s=><div className="v6row" key={s.id}><b>{new Date(s.created_at).toLocaleString()}</b><br/><small>{s.analysis}</small></div>):<p>No screenshot history yet.</p>}</Card>}
  </div>
}
function Card({title,children}){return <div className="v6card"><h3>{title}</h3>{children}</div>}
const css=`.v6{background:#0b1020;border:1px solid #28406e;border-radius:14px;padding:14px;margin:14px;color:#e8e8f4}.v6top{display:flex;justify-content:space-between;gap:10px}.v6 h2{color:#00f5ff;margin:0}.v6 p{font-size:12px;color:#a8a8c8}.v6actions,.v6tabs{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0}.v6 button{background:#111936;border:1px solid #28406e;color:#e8e8f4;border-radius:9px;padding:8px 10px;font-weight:700}.v6 button.a,.v6 button:hover{border-color:#00f5ff;color:#00f5ff}.v6card{background:#111936;border:1px solid #28406e;border-radius:12px;padding:12px;margin-top:10px}.v6card h3{color:#b026ff;margin:0 0 8px}.v6card pre{white-space:pre-wrap;max-height:300px;overflow:auto;background:#060914;border:1px solid #28406e;border-radius:8px;padding:8px;font-size:10px;color:#00f5ff}.v6grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.v6grid.mini{grid-template-columns:repeat(auto-fit,minmax(100px,1fr))}.v6summary{white-space:pre-wrap;background:#060914;border:1px solid #28406e;border-radius:8px;padding:10px;font-size:12px;line-height:1.55}.v6row{border-bottom:1px solid #28406e;padding:8px 0;font-size:12px;color:#a8a8c8}.v6note{border:1px solid #ff9100;color:#ff9100;border-radius:8px;padding:8px;margin:8px 0;font-size:12px}`;
